services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - '8001:8001'
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - credentials_db_data:/var/lib/postgresql/data

volumes:
  credentials_db_data:
