services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - '8001:8001'
    env_file:
      - .env
    depends_on:
      credential-db:
        condition: service_healthy
    networks:
      app-network:
        aliases:
          - credential-app

  credential-db:
    image: postgres:14
    restart: unless-stopped
    ports:
      - '5433:5432'
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  credentials_db_data:

networks:
  app-network:
    external: true
